"""Add indices for puzzle and puzzle_solve

Revision ID: 422e5e208f23
Revises: bab78ae6998a
Create Date: 2025-04-19 23:43:05.266977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422e5e208f23'
down_revision: Union[str, None] = 'bab78ae6998a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_puzzle_solves_profile_puzzle', 'puzzle_solves', ['profile_id', 'puzzle_id'], unique=False)
    op.create_index('idx_puzzles_rating_id', 'puzzles', ['rating', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_puzzles_rating_id', table_name='puzzles')
    op.drop_index('idx_puzzle_solves_profile_puzzle', table_name='puzzle_solves')
    # ### end Alembic commands ###
