"""Update default puzzle rating to 500

Revision ID: 7c367d5ccd8c
Revises: f7d289a6d63f
Create Date: 2025-04-17 12:42:29.433894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c367d5ccd8c'
down_revision: Union[str, None] = 'f7d289a6d63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        UPDATE profiles
        SET ratings = jsonb_set(ratings::jsonb, '{puzzle}', '500', true)
        WHERE (ratings->>'puzzle')::int != 500
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
