"""remove unique constraint from puzzle_solves

Revision ID: bab78ae6998a
Revises: be327dcfd896
Create Date: 2025-04-19 15:45:08.447146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab78ae6998a'
down_revision: Union[str, None] = 'be327dcfd896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_puzzle_per_profile', 'puzzle_solves', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_puzzle_per_profile', 'puzzle_solves', ['profile_id', 'puzzle_id'])
    # ### end Alembic commands ###
