"""add puzzle solves and active puzzle to profile

Revision ID: be327dcfd896
Revises: 7c367d5ccd8c
Create Date: 2025-04-19 14:45:16.884017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be327dcfd896'
down_revision: Union[str, None] = '7c367d5ccd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_deviation', sa.Float(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('times_played', sa.Integer(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('game_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puzzle_solves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.String(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('rating_before', sa.Float(), nullable=True),
    sa.Column('rating_after', sa.Float(), nullable=True),
    sa.Column('rating_delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'puzzle_id', name='unique_puzzle_per_profile')
    )
    op.add_column('profiles', sa.Column('active_puzzle_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'puzzles', ['active_puzzle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'active_puzzle_id')
    op.drop_table('puzzle_solves')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
