name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend_chess98/**'
      - 'deploy/frontend.yaml'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/chess98-fe:latest ./frontend_chess98
        docker push ${{ secrets.DOCKER_USERNAME }}/chess98-fe:latest

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

    - name: Apply frontend manifest
      run: kubectl --kubeconfig=kubeconfig.yaml apply -f deploy/frontend.yaml

    - name: Force redeploy frontend
      run: kubectl rollout restart deployment frontend --kubeconfig=kubeconfig.yaml